server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: micro-pacientes
          uri: lb://pacientes
          predicates:
            - Path=/pacientes/**
        - id: micro-medicos
          uri: ${SPRING_MEDICOS:lb://medicos}
          predicates:
            - Path=/medicos/**
        - id: micro-citas
          uri: lb://citas
          predicates:
            - Path=/citas/**
        - id: micro-consultador-historialmedico
          uri: lb://consultador-historialmedico
          predicates:
            - Path=/historiales/**
        - id: micro-consultador-facturas
          uri: lb://consultador-factura
          predicates:
            - Path=/facturas/**
    discovery:
      locator:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0 # Captura el 100% de las trazas
  zipkin:
    base-url: ${SPRING_ZIPKIN:http://localhost:9411} # Dirección del servicio Zipkin

eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_SERVER_URI:http://localhost:8761/eureka}