spring:
  application:
    name: consultador-factura
  cloud:
    config:
      uri: http://${HOST_CONFIG_SERVER:localhost}:8888

eureka:
  client:
    service-url:
      defaultZone: http://${HOST_EUREKA_SERVER:localhost}:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Activo el perfil default para que obtenga la configuración del Config Server
profiles:
  active: default