spring:
  application:
    name: consultador-facturas
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

# Activo el perfil default para que obtenga la configuración del Config Server
profiles:
  active: default