APPLICATION_ID: pacientes
service_description:
  name: pacientes-service
  version: 1.0.0
servicecomb:
  service:
    registry:
      address: http://127.0.0.1:30100
  rest:
    address: 0.0.0.0:8080
  highway:
    address: 0.0.0.0:7070