spring:
  sleuth:
    sampler:
      probability: 1.0 # Captura el 100% de las trazas
  zipkin:
    base-url: ${SPRING_ZIPKIN:http://localhost:9411} # Dirección del servicio Zipkin

management:
  endpoints:
    web:
      exposure:
        include: info
