server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: ${HOST_KAFKA:localhost}:9092
    producer:
      properties:
        key.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        value.serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
        schema.registry.url: http://${HOST_SCHEMA_REGISTRY:localhost}:8081
  datasource:
    url: jdbc:postgresql://${DB_CITAS:localhost}:${PORT_POSTGRE:5433}/citas_db
    username: citas_user
    password: citas_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Para formatear las consultas SQL en los logs
        use_sql_comments: true  # Añade comentarios en las consultas
        type:
          # Muestra los valores enlazados en las consultas
          descriptor:
            sql:
              BasicBinder: TRACE

info:
  app:
    name: Microservicio de Citas
    description: Este es el microservicio encargado de gestionar las citas y relacionarse con Kafka y otros microservicios.
    version: 1.0.0
    status: Activo

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Muestra los valores enlazados en las consultas
    org.springframework: INFO  # Ajusta según sea necesario para limitar la verbosidad
