server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/citas_db
    username: citas_user
    password: citas_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
