server:
  port: 8088

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: historial-medico-consumer
      auto-offset-reset: earliest
      properties:
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry.url: http://localhost:8081/
        specific.avro.reader: true
  data:
    mongodb:
      uri: mongodb://historialmedico_user:historialmedico_password@localhost:27017/historialmedico_db
