server:
  port: 8084

spring:
  data:
    mongodb:
      uri: ${SPRING_DATASOURCE_URL:mongodb://historialmedico_user:historialmedico_password@localhost:27017/historialmedico_db}

info:
  app:
    name: Microservicio de Consultador-HistorialMedico
    description: Este es el microservicio encargado de gestionar la devolución de los hisotriales médicos de los pacientes.
    version: 1.0.0
    status: Activo
