server:
  port: 8088

spring:
  kafka:
    bootstrap-servers: ${HOST_KAFKA:localhost}:9092
    consumer:
      specific-avro-reader: true
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      properties:
        key.deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
        value.deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
        schema.registry.url: http://${HOST_SCHEMA_REGISTRY:localhost}:8081
  data:
    mongodb:
      uri: mongodb://historialmedico_user:historialmedico_password@${DB_HISTORIALES:localhost}:${PORT_MONGO:27017}/historialmedico_db
