server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://${DB_FACTURAS:localhost}:${PORT_MYSQL:3308}/facturas_db?allowPublicKeyRetrieval=true&useSSL=false
    username: facturas_user
    password: facturas_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

info:
  app:
    name: Microservicio de Consultador-Facturas
    description: Este es el microservicio encargado de gestionar la devolución de los datos de las facturas.
    version: 1.0.0
    status: Activo

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Muestra los valores enlazados en las consultas
    org.hibernate.type.descriptor.sql: TRACE # Muestra los valores de los parámetros en las consultas
