server:
  port: 8088

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_SERVER:localhost:9092}
    consumer:
      specific-avro-reader: true
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      properties:
        key.deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
        value.deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
        schema.registry.url: ${SPRING_SCHEMA_REGISTRY:http://localhost:8081}
  data:
    mongodb:
      uri: ${SPRING_DATASOURCE_URL:mongodb://historialmedico_user:historialmedico_password@localhost:27017/historialmedico_db}
