server:
  port: 8088

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      specific-avro-reader: true
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      properties:
        key.deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
        value.deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
        schema.registry.url: http://localhost:8081
  data:
    mongodb:
      uri: mongodb://historialmedico_user:historialmedico_password@localhost:27017/historialmedico_db
