server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pacientes_db
    username: pacientes_user
    password: pacientes_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  eruka:
