server:
  port: 8086

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pacientes_db}
    username: pacientes_user
    password: pacientes_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

info:
  app:
    name: Microservicio de Paciente
    description: Este es el microservicio encargado de gestionar los pacientes.
    version: 1.0.0
    status: Activo
