server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: micro-pacientes
          uri: lb://pacientes
          predicates:
            - Path=/pacientes/**
    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka